// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.last_seen_buildid", "20200508232522");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.normandy.user_id", "ca83e905-e31c-4a9b-a754-99aba9ed7756");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1591844585);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1591844105);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1591844721);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1591844225);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1591844465);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1591844705);
user_pref("browser.cache.disk.amount_written", 23217);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.formfill.enable", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "[\"DuckDuckGo Lite\",\"Searx\",\"StartPage\",\"Jive Search\",\"Qwant\",\"MetaGer\",\"Invidious\"]");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/file/3521827/ublock_origin-1.26.2-an+fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200508232522");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1591844721");
user_pref("browser.slowStartup.averageTime", 1856);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "duckduckgo.com");
user_pref("browser.startup.lastColdStartupCheck", 1591844721);
user_pref("browser.startup.page", 3);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"home-button\",\"downloads-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"add-ons-button\",\"preferences-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\",\"jid1-zadieub7xozojw_jetpack-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"https-everywhere_eff_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\",\"jid1-zadieub7xozojw_jetpack-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"https-everywhere_eff_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "76.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.LibreWolf.bookmarksProcessed", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200508232522");
user_pref("extensions.lastAppVersion", "76.0.1");
user_pref("extensions.lastPlatformVersion", "76.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.https-everywhere@eff.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-MnnxcxisBPnSXQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-ZAdIEUB7XOzOJw@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"f781be66-7b1f-46ef-b5c7-66bea966cda8\",\"screenshots@mozilla.org\":\"3b9f46c9-577b-41e3-916b-3cb9b2a2a204\",\"default-theme@mozilla.org\":\"8457d36a-c37f-4976-88fb-f86cd5485bd6\",\"google@search.mozilla.org\":\"dc9289d2-4857-420a-9def-372039449e3b\",\"amazondotcom@search.mozilla.org\":\"d420a3b6-a6dc-41fc-9d72-9b37d32e3f3a\",\"bing@search.mozilla.org\":\"4a33ccac-0675-41fa-99fd-8a285fc45917\",\"ddg@search.mozilla.org\":\"7e1948aa-003b-47c1-93ac-396e25197d10\",\"ebay@search.mozilla.org\":\"c6731a51-a084-413e-884d-a5b70aca69de\",\"twitter@search.mozilla.org\":\"185dad85-0708-44b9-9978-a5bf87a065da\",\"wikipedia@search.mozilla.org\":\"f87b6776-1399-4c58-805a-820a0f4357a6\",\"uBlock0@raymondhill.net\":\"0ef66847-1ca1-4a87-b0a0-34b768232796\",\"jid1-ZAdIEUB7XOzOJw@jetpack\":\"21657d9d-4408-41b8-a0b3-1c6f2d9bdbe5\",\"jid1-MnnxcxisBPnSXQ@jetpack\":\"f8b72459-43c7-4c8d-bee7-d58a1e19cc70\",\"https-everywhere@eff.org\":\"57bd4c88-2f82-493f-8000-ecf94afe8ba0\"}");
user_pref("general.autoScroll", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.mode", 2);
user_pref("network.trr.uri", "https://mozilla.cloudflare-dns.com/dns-query");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.enabled", true);
user_pref("places.history.expiration.transient_current_max_pages", 2147483647);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.sanitizeOnShutdown", false);
user_pref("security.sandbox.content.tempDirSuffix", "b0f9324a-dbb5-4bbc-a60d-5adde468af51");
user_pref("security.sandbox.plugin.tempDirSuffix", "da97b458-8ed4-492d-9c3b-0669461148e0");
user_pref("services.settings.clock_skew_seconds", -646);
user_pref("services.settings.last_etag", "\"1591833678692\"");
user_pref("services.settings.last_update_seconds", 1591845111);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1591845111);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1591845111);
user_pref("services.settings.main.hijack-blocklists.last_check", 1591845111);
user_pref("services.settings.main.language-dictionaries.last_check", 1591845111);
user_pref("services.settings.main.messaging-experiments.last_check", 1591845111);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1591845111);
user_pref("services.settings.main.search-config.last_check", 1591845111);
user_pref("services.settings.main.sites-classification.last_check", 1591845111);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1591845111);
user_pref("signon.importedFromSqlite", true);
user_pref("startup.homepage_override_url", "about:blank");
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("toolkit.startup.last_success", 1591844719);
user_pref("toolkit.telemetry.cachedClientID", "20ee6a2e-ecce-4a2d-be57-8c418edb30e0");
