#Environment variables to move files out of home directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export INPUTRC="${XDG_CONFIG_HOME}/readline/inputrc"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/lesskey"
export npm_config_cache="${XDG_CACHE_HOME}/npm"
export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
export CARGO_HOME="${XDG_CACHE_HOME}/cargo"
export GIMP2_DIRECTORY="${XDG_CONFIG_HOME}/gimp"
export ANDROID_HOME="$XDG_DATA_HOME/android"
export CCACHE_DIR="${XDG_CACHE_HOME}/ccache"
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
export PLATFORMIO_CORE_DIR="$XDG_DATA_HOME/platformio"
export SQLITE_HISTORY="$XDG_CACHE_HOME/sqlite_history"
export WINEPREFIX="$XDG_DATA_HOME/wine"
export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"
export DVDCSS_CACHE="$XDG_DATA_HOME/dvdcss"
export ANDROID_USER_HOME="$XDG_DATA_HOME/android"